pipeline {
  agent any

  environment {
    DOCKER_REGISTRY = "docker.io"
    DOCKER_REPO     = "hragab211/hossam-portfolio"   // change if your repo name differs
    DOCKER_CREDS    = "dockerhub-creds"
    GIT_URL         = "https://github.com/HRagab211/portfolio.git" // <-- CHANGE
    GIT_BRANCH      = "main"
  }

  options {
    timestamps()
    disableConcurrentBuilds()
  }

  triggers {
    pollSCM('H/2 * * * *')   // every 2 minutes
  }

  stages {
    stage("Checkout main") {
      steps {
        git branch: "${GIT_BRANCH}", url: "${GIT_URL}"
      }
    }

    stage("Generate Version") {
      steps {
        script {
          def shortSha = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
          env.IMAGE_TAG = "v${env.BUILD_NUMBER}-${shortSha}"
          echo "Image tag: ${env.IMAGE_TAG}"
        }
      }
    }

    stage("Build Docker Image") {
      steps {
        sh """
          docker build -t ${DOCKER_REPO}:${IMAGE_TAG} .
          docker tag ${DOCKER_REPO}:${IMAGE_TAG} ${DOCKER_REPO}:latest
        """
      }
    }

    stage("Push Docker Image") {
      steps {
        withCredentials([usernamePassword(
          credentialsId: DOCKER_CREDS,
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh """
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin ${DOCKER_REGISTRY}
            docker push ${DOCKER_REPO}:${IMAGE_TAG}
            docker push ${DOCKER_REPO}:latest
            docker logout ${DOCKER_REGISTRY}
          """
        }
      }
    }
  }

  post {
    success {
      echo "✅ Pushed ${DOCKER_REPO}:${IMAGE_TAG} and :latest"
    }
  }
}